---
title: "Plotting Assignment - "
author: "Gian Wegmueller"
date: "`r format(Sys.time(), '%d %B, %Y')`"
output:
  html_document:
    code_folding: show
    highlight: haddock
    theme: flatly
    toc: yes
    toc_float: yes
---

```{r, include=FALSE}

# set knit options
knitr::opts_chunk$set(message = FALSE,
                      warning = FALSE)

# disable scientific notation
options(scipen = 999) 


```

# Dependencies

```{r}

# update dependencies -> only include necessary packages

library(readr)
library(dplyr)
library(tidyr)
library(janitor)
library(stringr)
library(trackeR)
library(ggplot2)


library(datasauRus) 
library(scales)

library(plotrix) 
library(ThemePark)
library(patchwork)

library(knitr)
library(kableExtra)

```


# Data exploration (temporary, should not be included in final file)

```{r Data exploration}
## Drug use data
drugs_raw <- read_csv("../data/drug_use_by_age.csv")


```

## Data Preparation Drug Use

```{r Data prep}
drugs_comparison <- drugs_raw %>% 
  select(age, n, 
         starts_with(c("alcohol", "marijuana", "cocaine", "meth"))) %>% 
  filter(age %in% c("21", "22-23", "24-25", "26-29", "50-64")) %>% #choosing only legal drinking-age millenials for comparison here!
  mutate(cocaine_frequency = as.numeric(cocaine_frequency),
         meth_frequency = as.numeric(meth_frequency),
         generation = if_else(age == "50-64", "Boomers", "Millennials")) %>% 
  group_by(generation) %>% 
  summarize(booze_med_freq = janitor::round_half_up(weighted.mean(alcohol_frequency, n), 1),
            pot_med_freq = janitor::round_half_up(weighted.mean(marijuana_frequency, n), 1),
            coke_med_freq = janitor::round_half_up(weighted.mean(cocaine_frequency, n), 1),
            meth_med_freq = janitor::round_half_up(weighted.mean(meth_frequency, n), 1)) %>% 
  pivot_longer(cols = booze_med_freq:meth_med_freq,
               names_to = "drug",
               values_to = "median_freq")

```

## Data Visualization Median Use Frequency

```{r Visualization}

# Bad plot for visualizing median use frequency of 4 different drugs by generation (Boomers & Millennials)
drug_use_plot <- ggplot(data = drugs_comparison,
                 aes(x = median_freq,
                     y = drug,
                     colour = generation)) +
  
  geom_bin_2d(position = "stack", 
              binwidth = 5,
              fill = "#FF5F1F",
              show.legend = TRUE) +
  
  geom_line(mapping = aes(group = generation),
            linewidth = .2) +
  
  scale_colour_manual(values = c("#00BFFF", "#00827F")) + 
  
  scale_x_continuous(breaks = seq(0, 60, 2.3),
                     limits = c(0, 60)) +
  
  labs(title = "Median Use Frequency by Generation",
       x = "Median Use Frequency", 
       y = "",
       colour = "Generation") +
  
  theme_dark(base_family = "serif")
  

drug_use_plot
```

# Visualizing Heart Rate Data from the Lucerne Half-Marathon 2024

## Data Preparation Lucerne Half-Marathon
Personal heart rate zones at the time of the race were: 

- Zone 1: 98 - 116 bpm
- Zone 2: 117 - 136 bpm
- Zone 3: 137 - 155 bpm
- Zone 4: 156 - 175 bpm
- Zone 5: >= 176 bpm



```{r}
lucerne_half_24 <- readTCX("../data/lucerne_half_2024.tcx")

lucerne_half_24_bpm <- lucerne_half_24 %>% 
  select(altitude, distance, heart_rate) %>% 
  mutate(distance_km = distance/1000,
         heart_rate_zone = case_when(heart_rate >= 98 & heart_rate <= 116 ~ "Zone 1",
                                     heart_rate >= 117 & heart_rate <= 136 ~ "Zone 2",
                                     heart_rate >= 137 & heart_rate <= 155 ~ "Zone 3",
                                     heart_rate >= 156 & heart_rate <= 175 ~ "Zone 4",
                                     heart_rate >= 176 ~ "Zone 5")) %>% 
  relocate(distance_km, distance, altitude, heart_rate, heart_rate_zone)



```


# Session info

```{r}

sessionInfo()

```
